name: shoppingapp
description: Shopping App
version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^2.1.0
  badges: ^2.0.1
  bot_toast: ^4.0.1
  bubble_tab_indicator: ^0.1.6
  carousel_slider: ^4.0.0
  clippy_flutter: ^1.1.1
  connectivity: ^3.0.6
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.3
  dropdown_search: ^0.6.3
  expandable: ^5.0.1
  flutter_countdown_timer: ^4.1.0
  flutter_icons: ^1.1.0
  flutter_image_compress: ^1.0.0
  flutter_material_color_picker: ^1.0.5
  flutter_phoenix: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_statusbarcolor: ^0.2.3
  getflutter: ^1.1.3
  intl: ^0.17.0
  like_button: ^2.0.2
  loading_indicator:
  marquee: ^2.2.0
  multi_image_picker: ^4.7.14
  page_transition: ^2.0.2
  path: ^1.8.0
  path_provider:
  provider: ^5.0.0
  razorpay_flutter: ^1.2.7
  rflutter_alert: ^2.0.2
  rxdart: ^0.27.1
  searchable_dropdown: ^1.1.3
  shared_preferences: ^2.0.6
  get: ^4.6.1
  flutter_document_picker: ^4.0.1
  validators: ^3.0.0
  signature: ^4.1.1
  url_launcher: ^6.0.9
  firebase_crashlytics: ^2.0.7
  firebase_core: ^1.3.0
  file_picker: ^1.4.3+2
  flutter_svg: ^0.22.0
  flutter_translate: ^3.0.1
  google_fonts: ^2.1.0
  http: ^0.13.0
  image_picker:
  store_redirect: ^2.0.0
  package_info:
  shimmer: ^2.0.0

  permission_handler:

  dio: ^4.0.0
  photo_view: ^0.13.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/i18n/
    - assets/bannerimages/
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

























